import { App, TFile } from 'obsidian';
import { BaseGenerator } from './base';
import { VaultInsightsSettings, GeneratedNote, SummaryStats } from '../types';
import { OllamaClient } from '../integrations/ollama';
import { topicDistributionChart, emptyStateMessage } from '../visualizations';

/**
 * Generator for daily summary notes
 */
export class DailySummaryGenerator extends BaseGenerator {
	private date: Date;

	constructor(
		app: App,
		settings: VaultInsightsSettings,
		ollamaClient?: OllamaClient,
		date?: Date
	) {
		super(app, settings, ollamaClient);
		this.date = date ?? new Date();
	}

	async generate(): Promise<GeneratedNote> {
		const stats = this.gatherDailyStats();
		const aiSummary = await this.generateAISummary(stats.files);
		const wordCountStats = await this.getWordCountStats(stats.files);

		const endDateStr = this.formatDate(this.date);
		const lookbackDays = Math.max(1, this.settings.dailyLookbackDays);
		const startDate = new Date(this.getStartOfDay(this.date).getTime() - (lookbackDays - 1) * 24 * 60 * 60 * 1000);
		const startDateStr = this.formatDate(startDate);
		const title = `Daily summary - ${endDateStr}`;
		const { summaryFolder } = this.settings;

		const note: GeneratedNote = {
			title,
			path: `${summaryFolder}/Daily/${title}.md`,
			content: this.buildContent(stats, aiSummary, wordCountStats),
			frontmatter: {
				title,
				generated: this.getISOTimestamp(),
				generator: 'daily-summary',
				period: 'daily',
				startDate: startDateStr,
				endDate: endDateStr,
				tags: ['vault-insights', 'daily-summary'],
			},
		};

		await this.save(note);
		this.notify('Daily summary created!');
		return note;
	}

	private gatherDailyStats(): SummaryStats {
		const lookbackDays = Math.max(1, this.settings.dailyLookbackDays);
		const endOfDay = this.getEndOfDay(this.date);
		const startOfPeriod = this.getStartOfDay(
			new Date(endOfDay.getTime() - (lookbackDays - 1) * 24 * 60 * 60 * 1000)
		);

		const createdFiles = this.getFilesCreatedBetween(startOfPeriod.getTime(), endOfDay.getTime());
		const modifiedFiles = this.getFilesModifiedBetween(startOfPeriod.getTime(), endOfDay.getTime());
		const files = [...new Set([...createdFiles, ...modifiedFiles])];
		const { total, completed } = this.countTasksInFiles(files);
		const createdPaths = new Set(createdFiles.map(file => file.path));
		const modifiedOnlyCount = modifiedFiles.filter(file => !createdPaths.has(file.path)).length;

		return {
			notesCreated: createdFiles.length,
			notesModified: modifiedOnlyCount,
			totalTasks: total,
			completedTasks: completed,
			topTopics: this.extractTopicsFromFiles(files),
			files,
		};
	}

	/**
	 * Generate an AI summary from modified files using Ollama.
	 * Returns null if Ollama is unavailable or disabled.
	 */
	private async generateAISummary(files: TFile[]): Promise<string | null> {
		if (files.length === 0) return null;
		const content = await this.gatherContentForAI(files, 10, 500);
		return this.summarizeWithOllamaFallback(content);
	}

	/**
	 * Get the weekly summary link for this date
	 */
	private getWeeklySummaryLink(): string | null {
		const { weeklyUseCalendarWeeks, weeklyLookbackDays } = this.settings;
		const endOfPeriod = weeklyUseCalendarWeeks ? this.getEndOfWeek(this.date) : this.getEndOfDay(this.date);
		const startOfPeriod = weeklyUseCalendarWeeks
			? this.getStartOfWeek(this.date)
			: this.getStartOfDay(
				new Date(endOfPeriod.getTime() - (Math.max(1, weeklyLookbackDays) - 1) * 24 * 60 * 60 * 1000)
			);
		const startStr = this.formatDate(startOfPeriod);
		const endStr = this.formatDate(endOfPeriod);
		const weeklyTitle = `Weekly summary - ${startStr} to ${endStr}`;
		const weeklyPath = `${this.settings.summaryFolder}/Weekly/${weeklyTitle}.md`;

		// Check if weekly summary exists
		const exists = this.app.vault.getAbstractFileByPath(weeklyPath);
		if (exists) {
			return this.wikilink(weeklyPath, weeklyTitle);
		}
		return null;
	}

	private buildContent(
		stats: SummaryStats,
		aiSummary: string | null,
		wordCountStats: { totalWords: number; mostActiveNote: TFile | null; mostActiveWordCount: number }
	): string {
		const { notesCreated, notesModified, totalTasks, completedTasks, files, topTopics } = stats;
		const { totalWords, mostActiveNote, mostActiveWordCount } = wordCountStats;
		const { showAISummary, showCharts, showFileList, showTopicTable, maxChartItems, chartType, dailyLookbackDays } = this.settings;
		const chartsEnabled = showCharts;
		const notesSectionTitle = dailyLookbackDays > 1 ? 'Notes touched in period' : 'Notes touched today';
		const sections: string[] = [
			`# Daily summary - ${this.formatDateDisplay(this.date)}`,
			'',
		];

		// Add navigation to weekly summary if it exists
		const weeklyLink = this.getWeeklySummaryLink();
		if (weeklyLink) {
			sections.push(`*Part of ${weeklyLink}*`, '');
		}

		if (showAISummary && aiSummary) {
			sections.push(
				'## AI summary',
				'',
				'> [!note] Generated by Ollama',
				`> ${aiSummary}`,
				''
			);
		}

		sections.push(
			'## Overview',
			'',
			'| Metric | Value |',
			'|--------|-------|',
			`| Notes created | ${notesCreated} |`,
			`| Notes modified | ${notesModified} |`,
			`| Words written | ${totalWords.toLocaleString()} |`,
			`| Total tasks | ${totalTasks} |`,
			`| Completed tasks | ${completedTasks} |`,
			''
		);

		// Add most active note if available
		if (mostActiveNote && mostActiveWordCount > 0) {
			sections.push(
				`**Most active note:** ${this.wikilink(mostActiveNote.path)} (${mostActiveWordCount.toLocaleString()} words)`,
				''
			);
		}

		if (showFileList) {
			sections.push(
				`## ${notesSectionTitle}`,
				'',
				files.length === 0
					? emptyStateMessage('notes')
					: files.map(file => `- ${this.wikilink(file.path)}`).join('\n'),
				''
			);
		}

		if (chartsEnabled || showTopicTable) {
			sections.push('## Topics', '');

			if (topTopics.length === 0) {
				sections.push(emptyStateMessage('topics'), '');
			} else {
				if (chartsEnabled) {
					sections.push(topicDistributionChart(topTopics, maxChartItems, chartType), '');
				}
				if (showTopicTable) {
					sections.push(
						'| Rank | Topic | Count | Source |',
						'|------|-------|-------|--------|',
						...topTopics.slice(0, 10).map((topic, i) =>
							`| ${i + 1} | ${this.escapeTableCell(topic.name)} | ${topic.count} | ${topic.source} |`
						),
						''
					);
				}
			}
		}

		return sections.join('\n');
	}
}
