import { TFile } from 'obsidian';

// ============================================================================
// Type Aliases
// ============================================================================

/**
 * Sources for topic extraction
 */
export type TopicSource = 'tags' | 'headings' | 'links';

/**
 * Chart rendering engine
 */
export type ChartType = 'mermaid' | 'chartjs';

/**
 * How to group aggregated items
 */
export type GroupBy = 'file' | 'date' | 'tag';

/**
 * Task completion status
 */
export type TaskStatus = 'pending' | 'completed';

// ============================================================================
// Settings Interface
// ============================================================================

/**
 * Plugin settings stored in data.json
 */
export interface VaultInsightsSettings {
  // Summary settings
  summaryFolder: string;
  dailySummaryEnabled: boolean;
  weeklySummaryEnabled: boolean;
  summaryTime: string;
  dailyLookbackDays: number;
  weeklyLookbackDays: number;

  // Todo settings
  todoSourceFolders: string[];
  todoExcludeFolders: string[];
  todoGroupBy: GroupBy;
  todoIncludeCompleted: boolean;

  // Topic settings
  topicSources: TopicSource[];
  maxTopics: number;
  excludedTags: string[];

  // Ollama settings
  ollamaEnabled: boolean;
  ollamaUrl: string;
  ollamaModel: string;

  // Visualization settings
  chartType: ChartType;
  maxChartItems: number;
}

/**
 * Default plugin settings
 */
export const DEFAULT_SETTINGS: VaultInsightsSettings = {
  // Summary settings
  summaryFolder: 'Insights',
  dailySummaryEnabled: true,
  weeklySummaryEnabled: true,
  summaryTime: '09:00',
  dailyLookbackDays: 1,
  weeklyLookbackDays: 7,

  // Todo settings
  todoSourceFolders: [],
  todoExcludeFolders: ['templates', 'archive'],
  todoGroupBy: 'file',
  todoIncludeCompleted: false,

  // Topic settings
  topicSources: ['tags', 'headings'],
  maxTopics: 20,
  excludedTags: [],

  // Ollama settings
  ollamaEnabled: false,
  ollamaUrl: 'http://localhost:11434',
  ollamaModel: 'llama3',

  // Visualization settings
  chartType: 'mermaid',
  maxChartItems: 10,
};

// ============================================================================
// Extraction Result Interfaces
// ============================================================================

/**
 * A task extracted from a note
 */
export interface ExtractedTask {
  text: string;
  status: TaskStatus;
  line: number;
  filePath: string;
  fileName: string;
  tags: string[];
  dueDate?: Date;
}

/**
 * A topic identified from vault analysis
 */
export interface ExtractedTopic {
  name: string;
  type: TopicSource;
  count: number;
  files: string[];
}

/**
 * Content summary extracted from a note
 */
export interface ExtractedContent {
  filePath: string;
  fileName: string;
  headings: string[];
  firstParagraph: string;
  wordCount: number;
  createdAt: number;
  modifiedAt: number;
}

// ============================================================================
// Metadata Interfaces
// ============================================================================

/**
 * Information about a heading in a note
 */
export interface HeadingInfo {
  text: string;
  level: number;
  line: number;
}

/**
 * Information about a task in a note
 */
export interface TaskInfo {
  text: string;
  completed: boolean;
  line: number;
}

/**
 * Full metadata extracted from a note using MetadataCache
 */
export interface NoteMetadata {
  filePath: string;
  fileName: string;
  frontmatter: Record<string, unknown>;
  tags: string[];
  links: string[];
  headings: HeadingInfo[];
  tasks: TaskInfo[];
  createdAt: number;
  modifiedAt: number;
}

// ============================================================================
// Scanner Interfaces
// ============================================================================

/**
 * Filters for scanning the vault
 */
export interface ScanFilters {
  folders?: string[];
  excludeFolders?: string[];
  modifiedAfter?: number;
  modifiedBefore?: number;
}

/**
 * Result of a vault scan operation
 */
export interface ScanResult {
  files: TFile[];
  totalCount: number;
  scannedAt: number;
  filters: ScanFilters;
}

// ============================================================================
// Generated Output Interfaces
// ============================================================================

/**
 * A note generated by the plugin
 */
export interface GeneratedNote {
  title: string;
  path: string;
  content: string;
  frontmatter: Record<string, unknown>;
  generatedAt: number;
}

// ============================================================================
// Cache Interfaces
// ============================================================================

/**
 * A cached entry with metadata for invalidation
 */
export interface CacheEntry<T> {
  data: T;
  mtime: number;
  cachedAt: number;
}
